# Generated by Django 4.1 on 2022-08-30 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("nickname", models.CharField(blank=True, max_length=20)),
                ("cel", models.CharField(max_length=15)),
                ("mail", models.EmailField(max_length=254)),
                ("register_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="contacts.category",
                    ),
                ),
            ],
        ),
    ]
